#!/bin/bash

set -e

PROD_DIR=/groups/dungeons/pipeline
LOCAL_DIR=$(git rev-parse --show-toplevel)
BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Create symlink if Axiom folder does not exist
if [[ ! -d "${LOCAL_DIR}/pipeline/lib/axiom" ]]; then
    ln -s "${PROD_DIR}/pipeline/lib/axiom" "${LOCAL_DIR}/pipeline/lib/axiom"
fi

# Update the env file
if [[ "${PROD_DIR}" != "${LOCAL_DIR}" ]]; then
    cp "${PROD_DIR}/pipeline/env.py" "${LOCAL_DIR}/pipeline/env.py"
    cp "${PROD_DIR}/pipeline/env_sg.py" "${LOCAL_DIR}/pipeline/env_sg.py"
fi

# Update the venv and set it up if it doesn't exist
source "${LOCAL_DIR}/.githooks/update-venv"

# copy the pin shift tool over
if [[ "${PROD_DIR}" != "${LOCAL_DIR}" ]]; then
    cp "${PROD_DIR}/pipeline/software/maya/script/pin_shift.py" \
      "${LOCAL_DIR}/pipeline/software/maya/script/pin_shift.py"
fi
