#!/bin/bash

set -e

if ! [ -f ~/.local/bin/ruff ]; then
    python3.9 -m pip install ruff
fi

LOCAL_DIR=$(git rev-parse --show-toplevel)

echo "Formatting with ruff..."
~/.local/bin/ruff format "${LOCAL_DIR}"
