#!/bin/bash

set -e

LOCAL_DIR=$(git rev-parse --show-toplevel)

source "${LOCAL_DIR}/.githooks/update-venv"


echo "Static type checking (mypy)..."
mypy
echo "Linting (ruff)..."
ruff check "${LOCAL_DIR}"
echo "Formatting (ruff)..."
ruff format "${LOCAL_DIR}"
