#!/bin/bash
echo "Setting up dev venv..."

python3.9 -m venv "${LOCAL_DIR}/venv"
source "${LOCAL_DIR}/venv/bin/activate"

pip install --upgrade pip
pip install \
    maya-stubs \
    mypy \
    nptyping \
    ruff \
    types-usd \
    types-houdini \
    types-katana \
    types-mari \
    types-nuke \
    types-opencolorio \
    types-PySide2 \
    types-substance_painter

cat "${LOCAL_DIR}/.githooks/shotgun.pyi" > "${LOCAL_DIR}/pipeline/lib/shotgun_api3/shotgun_api3/__init__.pyi"
