#!/bin/bash
echo "Updating dev venv..."

command -v pipx || { 
    python3 -m pip install --user pipx && python3 -m pipx ensurepath 
}
command -v poetry || pipx install poetry
pipx upgrade poetry

PROD_DIR=/groups/dungeons/pipeline
LOCAL_DIR=$(git rev-parse --show-toplevel)

if [[ "${PROD_DIR}" == "${LOCAL_DIR}" ]]; then
    poetry sync --without dev
else
    poetry sync
fi

if [ -z "${VIRTUAL_ENV}" ]; then
    source "${LOCAL_DIR}/.venv/bin/activate"
fi

cat "${LOCAL_DIR}/.githooks/shotgun.pyi" > "${LOCAL_DIR}/pipeline/lib/shotgun_api3/shotgun_api3/__init__.pyi"
