global proc shelf_Test () {
    global string $gBuffStr;
    global string $gBuffStr0;
    global string $gBuffStr1;


    shelfButton
        -enableCommandRepeat 1
        -flexibleWidthType 3
        -flexibleWidthValue 32
        -enable 1
        -width 35
        -height 34
        -manage 1
        -visible 1
        -preventOverride 0
        -annotation "nothing" 
        -enableBackground 0
        -backgroundColor 0 0 0 
        -highlightColor 0.321569 0.521569 0.65098 
        -align "center" 
        -label "Apart" 
        -labelOffset 0
        -rotation 0
        -flipX 0
        -flipY 0
        -useAlpha 1
        -font "plainLabelFont" 
        -imageOverlayLabel "Apart Asset" 
        -overlayLabelColor 2.624876 0.801436 0.012446 
        -overlayLabelBackColor 0.227129 0.227129 0.227129 0.5 
        -image "createContainer.png" 
        -image1 "createContainer.png" 
        -style "iconOnly" 
        -marginWidth 0
        -marginHeight 1
        -command "from pipe.asset import apart; apart();" 
        -sourceType "python" 
        -commandRepeatable 1
        -flat 1
    ;

} 
